version: '3'
services:
  django:
    container_name: django_admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  pgdb:
    image: postgres:13
    container_name: my_pg_13
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_db
    build:
      context: .
      dockerfile: Dockerfile_pg
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - service
    ports:
      - "80:80"
