version: '3'
services:
  django:
    container_name: django_admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  pgdb:
    image: postgres:13-alpine
    container_name: my_pg_13
    env_file:
      - config/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.2
    container_name: my-nginx
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/configs:/etc/nginx/conf.d:ro
      - ./static:/data/static
    depends_on:
      - django
    ports:
      - "80:80"