version: '3'
services:
#  pgdb:
#    image: postgres:13
#    container_name: my_pg_13
#    environment:
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=123qwe
#      - POSTGRES_DB=movies_db
#    build:
#      context: .
#      dockerfile: Dockerfile_pg
#    volumes:
#      - $HOME/postgresql/data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  movies:
    container_name: django_admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#
#  nginx:
#    image: nginx:1.19.2
#    container_name: my-nginx
#    volumes:
#      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./src/configs:/etc/nginx/conf.d:ro
#    depends_on:
#      - movies
#    ports:
#      - "80:80"
